# Generated by Django 4.2.5 on 2023-10-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_document_id_alter_subject_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNo', models.IntegerField()),
                ('Dept', models.CharField(max_length=80)),
                ('Title', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=80)),
                ('PublishedBy', models.CharField(max_length=80)),
                ('Edition', models.CharField(max_length=80)),
                ('TotalVol', models.IntegerField()),
                ('RefVol', models.IntegerField()),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
