# Generated by Django 4.2.5 on 2023-10-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
