# Generated by Django 4.2.5 on 2023-10-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_rename_books_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='SNo',
            new_name='Sno',
        ),
    ]
