# Generated by Django 4.2.5 on 2023-10-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_book_author_alter_book_edition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Edition',
        ),
        migrations.RemoveField(
            model_name='book',
            name='PublishedBy',
        ),
        migrations.RemoveField(
            model_name='book',
            name='RefVol',
        ),
        migrations.RemoveField(
            model_name='book',
            name='TotalVol',
        ),
        migrations.AddField(
            model_name='book',
            name='Location',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
