# Generated by Django 4.2.5 on 2023-11-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_remove_book_edition_remove_book_publishedby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PQP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regulation', models.CharField(max_length=10)),
                ('Semester', models.IntegerField()),
                ('Branch', models.CharField(max_length=10)),
                ('link', models.URLField()),
            ],
            options={
                'db_table': 'pqp',
            },
        ),
    ]
