# Generated by Django 4.2.5 on 2023-11-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_pqp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqp',
            name='Subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
