# Generated by Django 4.2.5 on 2023-11-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_pqp_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqp',
            name='Year',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
