# Generated by Django 4.2.5 on 2023-11-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_pqp_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pqp',
            old_name='link',
            new_name='Link',
        ),
        migrations.AlterModelTable(
            name='book',
            table='BOOKS',
        ),
        migrations.AlterModelTable(
            name='document',
            table='DOCUMENTS',
        ),
        migrations.AlterModelTable(
            name='pqp',
            table='PQP',
        ),
    ]
