# Generated by Django 4.2.5 on 2023-11-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_rename_link_pqp_link_alter_book_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regulation', models.CharField(max_length=10)),
                ('Semester', models.IntegerField()),
                ('Branch', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=100, null=True)),
                ('Year', models.CharField(max_length=15, null=True)),
                ('Link', models.URLField()),
            ],
            options={
                'db_table': 'PPT',
            },
        ),
    ]
