# Generated by Django 4.2.5 on 2023-11-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_ppt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppt',
            name='Semester',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pqp',
            name='Semester',
            field=models.CharField(max_length=10),
        ),
    ]
